Add a param that lets the put version number be read from a file

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -9,12 +9,6 @@ echo $BUILD_PIPELINE_NAME 1>&2
 echo $ATC_EXTERNAL_URL 1>&2
 
 PLATFORM=`uname`
-MD5_TOOL="md5sum"
-if [ $PLATFORM = "Darwin" ]; then
-  MD5_TOOL="md5"
-fi
-
-echo $MD5_TOOL 1>&2
 
 SCRIPT_INPUT="$(cat <&0)"
 
@@ -24,6 +18,7 @@ BASE_DIR=$(jq -r '.source.base_dir // ""' <<< $SCRIPT_INPUT)
 USER=$(jq -r '.source.user // ""' <<< $SCRIPT_INPUT)
 SYNC_DIR=$(jq -r '.params.sync_dir // ""' <<< $SCRIPT_INPUT)
 RSYNC_OPTS_ARR=$(jq -r '.params.rsync_opts // ""' <<< $SCRIPT_INPUT)
+VERSION_FILE=$(jq -r '.params.version_file // ""' <<< $SCRIPT_INPUT)
 jq -re '.source.disable_version_path' <<< $SCRIPT_INPUT >/dev/null
 DISABLE_VERSION_PATH=$?
 
@@ -66,41 +61,51 @@ SSH_ASKPASS_REQUIRE=force \
   DISPLAY= \
   ssh-add ~/.ssh/server_key 1>&2 2>/dev/null
 
-VERSION_STRING="$BUILD_PIPELINE_NAME-$BUILD_ID"
-echo $VERSION_STRING 1>&2
+if [ -n "$VERSION_FILE" ]; then
+  VERSION_STRING="$(cat "$SRC_DIR/$VERSION_FILE")"
+else
+  MD5_TOOL="md5sum"
+  if [ $PLATFORM = "Darwin" ]; then
+    MD5_TOOL="md5"
+  fi
 
-MD5_STRING=`echo $VERSION_STRING | $MD5_TOOL | cut -d ' ' -f 1 `
+  VERSION_STRING="$BUILD_PIPELINE_NAME-$BUILD_ID"
+  echo "version_string=$MD5_TOOL($VERSION_STRING)" 1>&2
+
+  VERSION_STRING=$(echo $VERSION_STRING | $MD5_TOOL | cut -d ' ' -f 1 )
+fi
 if [ $? -eq 0 ]; then
-  echo $MD5_STRING 1>&2
-  
+  echo "version_string=$VERSION_STRING" 1>&2
+
   if [ $DISABLE_VERSION_PATH -eq 0 ]
   then
-      MD5_PATH=""
+      VERSION_PATH=""
   else
-      MD5_PATH=$MD5_STRING
+      VERSION_PATH=$VERSION_STRING
   fi
 
   # Create the new directory for this build
-  DEST_DIR=$BASE_DIR/$MD5_PATH
-  echo $DEST_DIR 1>&2
-  
+  DEST_DIR=$BASE_DIR/$VERSION_PATH
+  echo dest_dir=$DEST_DIR 1>&2
+
   REPORTED_VERSION=0
   for SERVER in $SERVERS
   do
-      CMD="ssh -i ~/.ssh/server_key -p $PORT $USER@$SERVER mkdir -p $DEST_DIR"
+      CMD="ssh -i ~/.ssh/server_key -p $PORT $USER@$SERVER mkdir -p '$DEST_DIR'"
       echo $CMD 1>&2
       eval $CMD 1>&2
-      
+
       if [ $? -eq 0 ]; then
-        RSYNC_CMD="rsync $RSYNC_OPTS -e 'ssh -i ~/.ssh/server_key -p $PORT'  $SRC_DIR/$SYNC_DIR/ $USER@$SERVER:$DEST_DIR"
+        RSYNC_CMD="rsync $RSYNC_OPTS -e 'ssh -i ~/.ssh/server_key -p $PORT'  '$SRC_DIR/$SYNC_DIR/' '$USER@$SERVER:$DEST_DIR'"
         echo $RSYNC_CMD 1>&2
 
         eval $RSYNC_CMD  1>&2
         if [ $? -eq 0 ]; then
             if [ $REPORTED_VERSION -eq 0 ]
             then
-                OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
+                OUTPUT_STRING="{ \"version\": { \"ref\": \"$VERSION_STRING\"} }"
                 echo $OUTPUT_STRING
+                echo output="$OUTPUT_STRING" 1>&2
                 REPORTED_VERSION=1
             fi
         else
@@ -113,6 +118,6 @@ if [ $? -eq 0 ]; then
       fi
   done
 else
-  echo "Failed to create MD5 hash" 1>&2
+  echo "Failed to create VERSION_STRING" 1>&2
   exit 1
 fi
